<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1619962406556' stop='1619962461013'>
    <name>Assign Leave for Vacation</name>
    <title>Assign Leave for Vacation</title>
    <test-cases>
        <test-case start='1619962406559' status='passed' stop='1619962412904'>
            <name>LoginPage</name>
            <title>LoginPage</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1619962412904' status='failed' stop='1619962447031'>
            <name>Add New Employee details</name>
            <title>Add New Employee details</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1619962447032' status='passed' stop='1619962455554'>
            <name>Add user details</name>
            <title>Add user details</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1619962455554' status='passed' stop='1619962460925'>
            <name>Assign leave for vacation</name>
            <title>Assign leave for vacation</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1619962460925' status='failed' stop='1619962461009'>
            <name>Login and verify leave</name>
            <title>Login and verify leave</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>NoSuchWindowError: no such window: target window already closed
                from unknown error: web view not found
                  (Session info: chrome=90.0.4430.93)</message>
                <stack-trace>NoSuchWindowError: no such window: target window already closed
                from unknown error: web view not found
                  (Session info: chrome=90.0.4430.93)
                    at Object.throwDecodedError (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:514:15)
                    at parseHttpResponse (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:519:13)
                    at C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)
                From: Task: WebDriver.takeScreenshot()
                    at thenableWebDriverProxy.schedule (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at thenableWebDriverProxy.takeScreenshot (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1085:17)
                    at run (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\built\browser.js:58:33)
                    at ProtractorBrowser.to.&lt;computed> [as takeScreenshot] (C:\Users\satya\AppData\Roaming\npm\node_modules\protractor\built\browser.js:66:16)
                    at C:\Users\satya\node_modules\protractor-jasmine2-screenshot-reporter\index.js:600:23
                    at C:\Users\satya\node_modules\lodash\lodash.js:4967:15
                    at baseForOwn (C:\Users\satya\node_modules\lodash\lodash.js:3032:24)
                    at C:\Users\satya\node_modules\lodash\lodash.js:4936:18
                    at Function.forEach (C:\Users\satya\node_modules\lodash\lodash.js:9410:14)
                    at Jasmine2ScreenShotReporter.specDone (C:\Users\satya\node_modules\protractor-jasmine2-screenshot-reporter\index.js:596:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>